# -*- mode: ruby -*-
# vi: set ft=ruby :

PEM_KEY                             = '/Users/vader/.vagrant.d/insecure_private_key'
ID_RSA                              = '/home/vagrant/.ssh/id_rsa'
HADOOP_MASTER_IP                    = '192.168.33.4'
HADOOP_DATANODE_1_IP                = '192.168.33.5'
HADOOP_DATANODE_2_IP                = '192.168.33.6'

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  # define Master server
    config.vm.define "hadoopmaster" do |hadoopmaster|
    hadoopmaster.vm.hostname = "hadoopmaster"
    hadoopmaster.vm.box = "bento/centos-7.1"
    #hadoopmaster.vm.synced_folder ".", "/home/vagrant", mount_options: ["dmode=775,fmode=664"]
    hadoopmaster.vm.network "private_network", ip: HADOOP_MASTER_IP
    hadoopmaster.vm.provider "virtualbox" do |v|
      v.name = "hadoopmasterr"
      v.cpus = 1
      v.memory = 1000
    end
    # copy private key so hosts can ssh using key authentication (the script below sets permissions to 600)
    hadoopmaster.vm.provision :file do |file|
      file.source      = PEM_KEY
      file.destination = ID_RSA
    end
    hadoopmaster.vm.provision "shell", path: "bootstrap.sh"
  end

  # define data1 server
    config.vm.define "hadoopdata1" do |hadoopdata1|
    hadoopdata1.vm.hostname = "hadoopdata1"
    hadoopdata1.vm.box = "bento/centos-7.1"
    hadoopdata1.vm.network "private_network", ip: HADOOP_DATANODE_1_IP
    hadoopdata1.vm.provider "virtualbox" do |v|
      v.name = "hadoopdata1"
      v.cpus = 1
      v.memory = 1000
    end
    # copy private key so hosts can ssh using key authentication (the script below sets permissions to 600)
    hadoopdata1.vm.provision :file do |file|
      file.source      = PEM_KEY
      file.destination = ID_RSA
    end
  end

  # define data2 server
  config.vm.define "hadoopdata2" do |hadoopdata2|
    hadoopdata2.vm.hostname = "hadoopdata2"
    hadoopdata2.vm.box = "bento/centos-7.1"
    hadoopdata2.vm.network "private_network", ip: HADOOP_DATANODE_2_IP
    hadoopdata2.vm.provider "virtualbox" do |v|
      v.name = "hadoopdata2"
      v.cpus = 1
      v.memory = 1000
    end
    # copy private key so hosts can ssh using key authentication (the script below sets permissions to 600)
    hadoopdata2.vm.provision :file do |file|
      file.source      = PEM_KEY
      file.destination = ID_RSA
    end
     
#  Run ansible script to provision cluster
   hadoopdata2.vm.provision "ansible" do |ansible|
      ansible.playbook       = "site.yml"
      ansible.verbose        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "inventory.yml"
   end
 
  end

end
